name = "LibWebSockets"
uuid = "fcb5309f-8123-4a11-8e81-3d7aa8197287"
authors = ["Samarin Aleksei <liotbiu1@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
